export const countryCodes: { [key: string]: string } = {
    '+1': 'United States',
    '+44': 'United Kingdom',
    '+33': 'France',
    '+49': 'Germany',
    '+81': 'Japan',
    '+86': 'China',
    '+91': 'India',
    '+61': 'Australia',
    '+7': 'Russia',
    '+34': 'Spain',
    '+39': 'Italy',
    '+82': 'South Korea',
    '+1-CA': 'Canada', 
    '+31': 'Netherlands',
    '+46': 'Sweden',
    '+64': 'New Zealand',
    '+41': 'Switzerland',
    '+971': 'United Arab Emirates',
    '+358': 'Finland',
    '+52': 'Mexico',
    '+55': 'Brazil',
    '+420': 'Czech Republic',
    '+45': 'Denmark',
    '+20': 'Egypt',
    '+30': 'Greece',
    '+852': 'Hong Kong',
    '+36': 'Hungary',
    '+62': 'Indonesia',
    '+353': 'Ireland',
    '+972': 'Israel',
    '+965': 'Kuwait',
    '+60': 'Malaysia',
    '+356': 'Malta',
    '+212': 'Morocco',
    '+234': 'Nigeria',
    '+47': 'Norway',
    '+63': 'Philippines',
    '+48': 'Poland',
    '+351': 'Portugal',
    '+974': 'Qatar',
    '+966': 'Saudi Arabia',
    '+65': 'Singapore',
    '+27': 'South Africa',
    '+66': 'Thailand',
    '+90': 'Turkey',
    '+84': 'Vietnam',
    '+260': 'Zambia',
    '+263': 'Zimbabwe',
};
